language: python

cache:
  - pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial

script:
    - pip install -r requirements.txt
    - pip install -e .
    - python setup.py test
